version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Monajat.Presentation/Dockerfile
    container_name: api
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnectionString: ""
    ports:


volumes:
  sqlserverdata:
